// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCha5LK9noC3e1OeySxZxIVvhl1Ox1i7ZQ',
    appId: '1:490474567720:web:a20c51d2233777de949d1d',
    messagingSenderId: '490474567720',
    projectId: 'yded-173f6',
    authDomain: 'yded-173f6.firebaseapp.com',
    databaseURL: 'https://yded-173f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yded-173f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkkUImuf6-J_CBupCCZ826WtW_VAuAiIk',
    appId: '1:490474567720:android:b0b47263bfc958fb949d1d',
    messagingSenderId: '490474567720',
    projectId: 'yded-173f6',
    databaseURL: 'https://yded-173f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yded-173f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0lWwmGp40PhlKbMn2ouHHL4_F-Rp5r7c',
    appId: '1:490474567720:ios:d61e83ed5e777819949d1d',
    messagingSenderId: '490474567720',
    projectId: 'yded-173f6',
    databaseURL: 'https://yded-173f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yded-173f6.appspot.com',
    androidClientId: '490474567720-okglm1bdp8nq31gejta3hfshuo2jv0kt.apps.googleusercontent.com',
    iosClientId: '490474567720-tca3829avhfgg8v4mug9sge9mun7594l.apps.googleusercontent.com',
    iosBundleId: 'com.example.yded',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0lWwmGp40PhlKbMn2ouHHL4_F-Rp5r7c',
    appId: '1:490474567720:ios:d61e83ed5e777819949d1d',
    messagingSenderId: '490474567720',
    projectId: 'yded-173f6',
    databaseURL: 'https://yded-173f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yded-173f6.appspot.com',
    androidClientId: '490474567720-okglm1bdp8nq31gejta3hfshuo2jv0kt.apps.googleusercontent.com',
    iosClientId: '490474567720-tca3829avhfgg8v4mug9sge9mun7594l.apps.googleusercontent.com',
    iosBundleId: 'com.example.yded',
  );
}
